export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const UPDATEAUTH = 'UPDATEAUTH';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const INITIATEUSER = 'INITIATEUSER';
export const UPDATEUSER = 'UPDATEUSER';
export const DELETEUSER = 'DELETEUSER';

export const INITIATEQUESTION = 'INITIATEACCOUNT';
export const UPDATEQUESTION = 'UPDATEACCOUNT';
export const DELETEQUESTION = 'DELETEACCOUNT';

export const INITIATETRADE = 'INITIATETRADE';
export const UPDATETRADE = 'UPDATETRADE';
export const DELETETRADE = 'DELETETRADE';

export const INITIATETRANSACTION = 'INITIATETRANSACTION';
export const UPDATETRANSACTION = 'UPDATETRANSACTION';
export const DELETETRANSACTION = 'DELETETRANSACTION';

export const INITIATESTOCKCODE = 'INITIATESTOCKCODE';
export const UPDATESTOCKCODE = 'UPDATESTOCKCODE';
export const DELETESTOCKCODE = 'DELETESTOCKCODE';
